name: Build and push

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  IMAGE_NAME: docker/babashka-pod-docker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Babashka
        run: |
          curl -sLO https://github.com/babashka/babashka/releases/download/v1.3.181/babashka-1.3.181-linux-amd64.tar.gz
          tar -xzf babashka-1.3.181-linux-amd64.tar.gz
          sudo mv bb /usr/local/bin

      - name: Run Clojure tests
        run: |
          bb -f test/run_all_tests.clj

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: dockerbuildbot
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            latest
            ${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
