name: Build and push

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  IMAGE_NAME: docker/babashka-pod-docker

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Babashka Pod binary
        run: |
          mkdir -p result/bin
          GOOS=linux GOARCH=amd64 go build -o result/bin/babashka-pod-docker .

      - name: Install Babashka
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo babashka/babashka --pattern "babashka-*-linux-amd64.tar.gz"
          FILE=$(ls babashka-*-linux-amd64.tar.gz)
          tar -xzf "$FILE"
          sudo mv bb /usr/local/bin/
          bb --version

      - name: Run Clojure tests
        run: bb test/run_all_tests.clj

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: dockerbuildbot
          password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            latest
            ${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
