name: Release and Docker Build

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: eduardot0/babashka-pod-docker  # ← Usamos tu repositorio Docker Hub

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Babashka
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          bb: latest

      - name: Build Babashka pod binary for tests
        run: |
          mkdir -p result/bin
          CGO_ENABLED=0 go build -ldflags "-s -w" -o result/bin/babashka-pod-docker

      - name: Run Clojure tests
        run: bb test/test_basic.clj

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-go-binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and release Go binaries
        uses: wangyoucao577/go-release-action@v1.35
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21.6
          binary_name: "babashka-pod-docker"
          release_tag: ${{ github.ref_name }}
          overwrite: true
          compress_assets: off
